--------------------------------------------------------------------------------------
-- Name	       : Call Center DB POC
-- Version     : 1.0
-- Last Updated: 10-06-2020
-- Notice      : The SQL queries is for demostration the poc of the project. 
--		 The datasource cannot be access due to confidential purpose.
--------------------------------------------------------------------------------------
--------------------------------------------------------------------


-- create user
CREATE USER OT IDENTIFIED BY xxxxxx;

-- grant priviledges
GRANT CONNECT, RESOURCE, DBA TO OT;

-- create database
CREATE DATABASE callcenterdb
USER SYS IDENTIFIED BY xxxxxx
USER SYSTEM IDENTIFIED BY xxxxxx
EXTENT MANAGEMENT LOCAL
DEFAULT TEMPORARY TABLESPACE temp
DEFAULT TABLESPACE users;


-- create tables
-- promotion tables
CREATE TABLE promotion
  (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 5 PRIMARY KEY,
    session_name VARCHAR2( 50 ) NOT NULL
  );

-- states table
CREATE TABLE states
  (
    state_id   CHAR( 2 ) PRIMARY KEY  ,
    state_name VARCHAR2( 40 ) NOT NULL,
    session_id NUMBER              , 
    CONSTRAINT fk_state_sessions FOREIGN KEY( session_id )
      REFERENCES sessions( session_id ) 
      ON DELETE CASCADE
  );


-- employees
CREATE TABLE employees
  (
    employee_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 108 
                PRIMARY KEY,
    first_name VARCHAR( 255 ) NOT NULL,
    last_name  VARCHAR( 255 ) NOT NULL,
    email      VARCHAR( 255 ) NOT NULL,
    phone      VARCHAR( 50 ) NOT NULL ,
    hire_date  DATE NOT NULL          ,
    job_title  VARCHAR( 255 ) NOT NULL,

  );


-- customers
CREATE TABLE customers
  (
    customer_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 320 
                PRIMARY KEY,
    name         VARCHAR2( 255 ) NOT NULL,
    address      VARCHAR2( 255 )         ,
    website      VARCHAR2( 255 )         ,
    credit_limit NUMBER( 8, 2 )
  );

-- calls
CREATE TABLE calls
  (
    call_id NUMBER 
               GENERATED BY DEFAULT AS IDENTITY START WITH 320 
               PRIMARY KEY,
    email       VARCHAR2( 255 ) NOT NULL,
    phone       VARCHAR2( 20 )          ,
    session_id CHAR( 2 )		,
    call_date date			,
    call_length VARCHAR2( 255 )		,
    call_handle VARCHAR2( 255 )		,
    holding VARCHAR2( 255 )		,
    employee_id NUMBER			,
    customer_id NUMBER                  ,
    CONSTRAINT fk_calls_customers 
      FOREIGN KEY( customer_id )
      REFERENCES customers( customer_id ) 
      ON DELETE CASCADE
  );



